PD-638: Documentation for installing license server
portworx/pxdocs pull request #948
Opened 2020-08-24 13:41 UTC by andreipope

First draft

2020-08-25 16:35 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install-pxcentral.md
> +If your cluster is internet-connected, skip this section. If your cluster is air-gapped, you must pull the Portworx license server and related Docker images to either your Docker registry, or your se
@bhavana-ar Should we remove "or your server"?

2020-08-25 16:53 UTC, andreipope commented
@bhavana-ar I have a few comments and questions as inline comments. Search for "<!--" to find them.

2020-09-18 21:40 UTC, nathan-px requested changes
I have some comments. Good job on keeping the screenshots consistent, they look great.

2020-09-18 21:40 UTC, nathan-px commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install-pxcentral.md
> +* PX-Central is installed with PX-Backup. <!-- Does this still apply?-->
Adding to this question, shouldn't it be the other way around -- `PX-Backup is installed with PX-Central`?

2020-09-18 21:40 UTC, nathan-px commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/monitor-clusters.md
> +From PX-Central, you can monitor one or more Portworx clusters.
I would welcome some more concept information here. Just make sure we keep it within the confines of PX-Central's monitoring functionality. Any broader concept information would be better off up a level. Also, we'll want to be careful to avoid just describing the UI elements. 

```suggestion
From PX-Central, you can monitor one or more Portworx clusters and see information such as:

* health of your nodes, volumes, and drives
* used and available capacity 
* current volumes, drives, pools, and snapshots

Using the monitoring page, you can ..

(who uses, why use, etc.)
```

2020-09-18 21:40 UTC, nathan-px commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/monitor-clusters.md
> +1. From the **PX-Central** home page, select the **Lighthouse** icon:
I also question the value of this task a bit. I'm worried we're just describing the UI here when it should just be intuitive. Do we know if this is a need driven by specific requests from support that we need a document to guide users to this page of their PX-Central UI? 

If not, I'd recommend we reframe this from a task to a concept topic. We can expand the concept information above and drop the task here.

2020-09-19 02:13 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/install-pxcentral.md
> +    * 50GB available `/root` disk size
I'd change ~/root~ to a generic _"disk space available"_
* the `/` is normally called "root partition" or "root mountpoint", while
* the `/root` is actually a root-user's home directory, and it's almost never a dedicated disk-partition
* the _actual_ disk-space is going to be required on `/var` partition (/var/lib/kubelet, /var/lib/docker, /var/lib/containerd -- depending on container-runtime), and `/var` is often a dedicated partition on enterprise clusters

2020-09-19 02:25 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/install-pxcentral.md
> +    bash <(curl -s https://raw.githubusercontent.com/portworx/px-central-onprem/<version>/install.sh) --px-store --px-backup --admin-password 'examplePassword' --oidc --pxcentral-namespace portworx -
This is a very unusual invocation for bootstrap-scripts.

Recommend to "break it up" into a more conservative "download + invoke" steps:
```sh
curl -s -o install.sh https://raw.githubusercontent.com/portworx/px-central-onprem/<version>/install.sh
bash ./install.sh --px-store --px-backup --admin-password 'examplePassword' \
    --oidc --pxcentral-namespace portworx                     \
    --px-license-server --license-password 'examplePassword'  \
    --px-backup-organization backup --cluster-name px-central \
    --admin-email admin@portworx.com --admin-user admin
```

2020-09-19 02:26 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/install-pxcentral.md
> +    `sudo iptables -P FORWARD ACCEPT`
might want to remove `-quotes, since this is already "in the box"

2020-09-19 02:31 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/upgrade/_index.md
> +    ./upgrade.sh
To stay consistent with the previous bootstrap-script, we might want to do the exact same invocation-style here:

```sh
curl -s -o upgrade.sh https://raw.githubusercontent.com/portworx/px-central-onprem/1.0.3/upgrade.sh
bash ./upgrade.sh
```
* note, quotation-marks with URL and "chmod" not required if ran like this

2020-09-19 02:36 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/upgrade/_index.md
> +    ./upgrade.sh
Oh, I see that we use the same `./upgrade.sh` also below.

Here's the deal--
* one can run the downloaded scripts via `bash script.sh`, and permission on the script-file will not matter
* if the script has execute-permission (i.e. `chmod a+x ./script.sh`), then it can be ran directly (i.e. `./script.sh --option1...`)

Not sure which "looks better" in the docs.

2020-09-19 02:39 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/upgrade/_index.md
> +    ./upgrade.sh
Also, let's please _not_ use `chmod +x` -- this is not portable and looks unusual.
More common usage is `chmod a+x`  (as in _"all set execute"_, "all" being user/group and "other").

2020-09-21 16:17 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install-pxcentral.md
>  * You must have [jq](https://stedolan.github.io/jq/) installed on the node where you will run the `install.sh` script
> We should remove the script mention. Is jq still a prereq?

Good catch, thanks!

2020-09-27 11:22 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/upgrade/_index.md
> +<!-- I think we should update this section as well. Do we have instructions for this? -->
@bhavana-ar

2020-09-28 10:27 UTC, tusharraut1994 requested changes

2020-09-28 10:27 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +    system:serviceaccount:<YOUR_NAMESPACE>:pxcentral-license-server
the command should be:
`system:serviceaccount:<YOUR_NAMESPACE>:px-monitor`

2020-09-28 10:27 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `persistentStorage.enabled` | Enables persistent storage | `false` |
Please, change this value from `false` to `true`

2020-09-28 11:18 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +    system:serviceaccount:<YOUR_NAMESPACE>:pxcentral-license-server
> the command should be:
> `system:serviceaccount:<YOUR_NAMESPACE>:px-monitor`

@tusharraut1994 Nice catch. Thanks!

2020-09-28 12:29 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/_index.md
> +2. Pull the following required Docker images onto your air-gapped environment: <!-- Is this list up-to-date? -->
@bhavana-ar @tusharraut1994

2020-09-28 12:30 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/_index.md
> +    <!-- Is the following still applicable? -->
@bhavana-ar @tusharraut1994

2020-09-28 12:30 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/_index.md
> +      * **Custom Registry**: The hostname of your custom registry <!-- needs validation-->
@bhavana-ar @tusharraut1994

2020-09-28 12:31 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +      * **Custom Registry**: The hostname of your custom registry <!-- needs validation-->
@bhavana-ar @tusharraut1994

2020-09-28 12:31 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +<!-- Should they use the `--set` flag to pass these arguments?  -->
@bhavana-ar @tusharraut1994

2020-09-28 12:32 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `pxlicenseserver.internal.lsTypeUAT` | Indicates the deployment type (UAT) <!-- I don't understand this --> | `false` |
@bhavana-ar @tusharraut1994

2020-09-28 12:32 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `pxlicenseserver.external.enabled` | Specifies whether this deployment uses an external license server <!-- Not sure I got this right--> | `false` |
@bhavana-ar @tusharraut1994

2020-09-28 12:32 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `images` | The list of Portworx images needed to install the license server component <!-- Not sure I got this right--> | |
@bhavana-ar @tusharraut1994

2020-09-28 12:32 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `images.pxLicenseHAConfigContainerImage.registry` | If you're running the license server in HA mode, this option indicates the registry for the configuration image <!-- Not sure I got this right-->
@bhavana-ar @tusharraut1994

2020-09-28 12:33 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `images.pxLicenseHAConfigContainerImage.repo` | If you're running the license server in HA mode, this option indicates the repository for the configuration image <!-- Not sure I got this right--> |
@bhavana-ar @tusharraut1994

2020-09-28 12:33 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `images.pxLicenseHAConfigContainerImage.imageName` | If you're running the license server in HA mode, this option indicates the name of the configuration image <!-- Not sure I got this right--> | `
@bhavana-ar @tusharraut1994

2020-09-28 12:33 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +      * **Custom Registry**: The hostname of your custom registry <!-- needs validation-->
@bhavana-ar @tusharraut1994

2020-09-28 12:34 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `pxmonitor.pxCentralEndpoint` | Indicates the endpoint of your PX-Central service <!-- Not sure I got this right--> | |
@bhavana-ar @tusharraut1994

2020-09-28 12:34 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `pxmonitor.sslEnabled` | Use this option to enable or disable HTTPS | `false` | `pxmonitor.oidcClientID` | The client ID for your OIDC provider <!-- Not sure I got this right--> | |
@bhavana-ar @tusharraut1994

2020-09-28 12:34 UTC, andreipope commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `installCRDs` | Install metrics stack required crds <!-- I don't understand this --> | `false` |
@bhavana-ar @tusharraut1994

2020-09-28 16:48 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install-pxcentral.md
> +2. Pull the following required Docker images onto your air-gapped environment: <!-- Is this list up-to-date? -->
Yes, images are changed:
https://github.com/portworx/helm/blob/master/charts/px-backup/values.yaml#L48-L107

2020-09-28 16:51 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/_index.md
> +2. Pull the following required Docker images onto your air-gapped environment: <!-- Is this list up-to-date? -->
Yes, images are changed
PX-Backup:
https://github.com/portworx/helm/blob/master/charts/px-backup/values.yaml#L48-L107
PX-Monitor:
https://github.com/portworx/helm/blob/master/charts/px-monitor/values.yaml#L34-L103
PX-License server:
https://github.com/portworx/helm/blob/master/charts/px-license-server/values.yaml#L23-L32

2020-09-28 16:51 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/_index.md
> +    <!-- Is the following still applicable? -->
Yes, we need to pull and push images to the registry for air-gapped install
PX-Backup:
https://github.com/portworx/helm/blob/master/charts/px-backup/values.yaml#L48-L107
PX-Monitor:
https://github.com/portworx/helm/blob/master/charts/px-monitor/values.yaml#L34-L103
PX-License server:
https://github.com/portworx/helm/blob/master/charts/px-license-server/values.yaml#L23-L32

2020-09-28 16:52 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +      * **Custom Registry**: The hostname of your custom registry <!-- needs validation-->
PX-License server:
https://github.com/portworx/helm/blob/master/charts/px-license-server/values.yaml#L23-L32

2020-09-28 16:53 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +<!-- Should they use the `--set` flag to pass these arguments?  -->
yes, they can use --set flat to overwrite default values.

2020-09-28 16:53 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `pxlicenseserver.internal.lsTypeUAT` | Indicates the deployment type (UAT) <!-- I don't understand this --> | `false` |
This flag is only for internal test, no need to expose.

2020-09-28 16:55 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/license-server/_index.md
> +| `pxlicenseserver.external.enabled` | Specifies whether this deployment uses an external license server <!-- Not sure I got this right--> | `false` |
If someone has a license server deployed on the external cluster or dedicated VMS or bare metals and want to configure with px-central they can use this option.

2020-09-28 16:55 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +      * **Custom Registry**: The hostname of your custom registry <!-- needs validation-->
PX-Monitor:
https://github.com/portworx/helm/blob/master/charts/px-monitor/values.yaml#L34-L103

2020-09-28 16:57 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `pxmonitor.pxCentralEndpoint` | Indicates the endpoint of your PX-Central service <!-- Not sure I got this right--> | |
Current pxcentral UI access endpoint. It can be IP:PORT or hostname

2020-09-28 16:58 UTC, tusharraut1994 commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/install/monitoring-service/_index.md
> +| `installCRDs` | Install metrics stack required crds <!-- I don't understand this --> | `false` |
For the new k8s cluster where no CRDs are registered we need to set this flag to install and register all required CRD's

2020-09-28 19:46 UTC, zoxpx commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/pxcentral-onprem/1-0-3/admin-pxcentral.md
> +    ./px-central-cleanup.sh
Quick note:
* we just downloaded the bootstrap with the previous step, and the bootstrap-script is lacking the execute-permission
* it can be ran indirectly via `bash px-central-cleanup.sh`, or
* if we add execute-permissions, it can also be ran directly, i.e. `chmod a+x px-central-cleanup.sh; ./px-central-cleanup.sh`

So, the statement above can be "fixed" by either "bash ..." or by running "chmod a+x ..." before running the script directly.

2020-09-29 16:46 UTC, bhavana-ar approved these changes

2020-09-29 17:02 UTC, merged