K3s support
portworx/pxdocs pull request #954
Opened 2020-08-28 13:04 UTC by andreipope

Signed-off-by: Andrei Popescu <andrei.popescu@gmail.com>

2020-09-18 17:11 UTC, nathan-px requested changes

2020-09-18 17:11 UTC, nathan-px commented on content/portworx-install-with-kubernetes/_index.md
> +[^1]: Limitation: you must use CSI integration to generate / use PVCs.
This footnote renders too far down, let's try adding it as a note to the cell (or beneath the table if it's too big)

<img width="685" alt="image" src="https://user-images.githubusercontent.com/53194370/93625728-4b7bbd80-f997-11ea-8a72-7864e379593c.png">

2020-10-05 05:42 UTC, andreipope commented on content/portworx-install-with-kubernetes/_index.md
> +[^1]: Limitation: you must use CSI integration to generate / use PVCs.
@nathan-px It is updated.

2020-10-14 09:32 UTC, nathan-px approved these changes

2020-10-14 14:59 UTC, merged