PD-651: Upgrade Portworx using Helm
portworx/pxdocs pull request #967
Opened 2020-09-14 14:31 UTC by andreipope

Signed-off-by: Andrei Popescu <andrei.popescu@gmail.com>

2020-09-18 17:03 UTC, nathan-px commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/upgrade/_index.md
> +**NOTE:** If you installed Portworx using Helm, enter the `helm upgrade` command to upgrade Portworx, specifying:
I'm not sure this should be a note. The command above is for the daemonset installation, I'm pretty sure. We will likely add an operator upgrade instruction here as well, so we should split this into subsections with headings.

2020-09-18 17:04 UTC, nathan-px requested changes
small change, see the note.

2020-09-24 05:17 UTC, andreipope commented
> small change, see the note.

@nathan-px It is updated.

2020-10-14 20:52 UTC, nathan-px approved these changes

2020-10-15 05:03 UTC, merged