PD-652: Add AWS Marketplace documentation
portworx/pxdocs pull request #971
Opened 2020-09-21 19:10 UTC by pault84

Signed-off-by: Paul <paul@portworx.com>

Added AWS Marketplace documentation.

2020-09-22 09:36 UTC, vinayakshnd commented
Need to release note PWX-15899

2020-09-22 09:39 UTC, vinayakshnd commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +| `maxStorageNodesPerZone` | Indicates the maximum number of storage nodes per zone. If this number is reached, and a new node is added to the zone, Portworx doesn’t provision drives for the new node
```suggestion
| `storage.maxStorageNodesPerZone` | Indicates the maximum number of storage nodes per zone. If this number is reached, and a new node is added to the zone, Portworx doesn’t provision drives for the new node. Instead, Portworx starts the node as a compute-only node. |
```

2020-09-22 13:17 UTC, vinayakshnd commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +| `secretType` | Secrets store to be used can be aws-kms/k8s/none defaults to: k8s |
@pault84 I dont think we support `secretType`. I dont see it anywhere in https://github.com/portworx/aws-helm/blob/master/templates/portworx-storagecluster.yaml

2020-09-22 17:55 UTC, pault84 commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +| `secretType` | Secrets store to be used can be aws-kms/k8s/none defaults to: k8s |
i added this

2020-09-22 20:33 UTC, nathan-px requested changes
See comments

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +#### Installation
I don't think there's any need for an "installation" heading directly beneath the "install" heading
```suggestion

```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/pre-reqs.md
> +Make sure to use the correct `namespace` and `serviceaccount`
Can you elaborate here? the heading and description don't tell the user what they're doing.

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +`storage.drives` has been set to 1 TB, if you wish to have smaller storage drives please change that setting.
This should be a note like the others

```suggestion
{{<info>}}
**NOTE:** 

* `clusterName` should be a unique name identifying your Portworx cluster. The default value is `mycluster`, but it is suggested to update it with your naming scheme.
* `storage.drives` has been set to 1 TB, if you wish to have smaller storage drives please change that setting.
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +The following tables lists the configurable parameters of the Portworx chart and their default values.
This reads like a reference. Do users actively need to configure things here? If so, we need to change this to a step format. i.e. something like: 

```
1. Specify the following configuration parameters individually using the `--set key=value[,key=value]` argument to `helm install`:

   `<!-- list parameters here -->`

   for a full list of configuration parameters, refer to the [Portworx helm install reference](link/to/reference/table) section.
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +#### Upgrading Portworx.
These should be a separate topic, probably under our existing upgrade/uninstall documents. We can link to them from this page by including a "## Related topics` section.

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +#### Un-installing Portworx
Drop the gerunds from headings, it shortens the words and, more importantly, makes the headings easier to parse when they're all together in a list, since they don't all end in the same 3 characters.

```suggestion
#### Uninstall Portworx
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +Edit the storage cluster.
These, and all other steps, should be numbered when they're tasks

```suggestion
1. Edit the storage cluster.
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +Add the following yaml under `spec:`
```suggestion
2. Add the following YAML under `spec:`
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +Save the spec and exit out.
```suggestion
3. Save the spec and exit out.
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +Then delete the storagecluster
can drop the adverb, simpler is better and the step is more portable.

```suggestion
4. Delete the storagecluster
```

2020-09-22 20:33 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/helm-install.md
> +Once all the portworx related pods are gone
```suggestion
5. Once all the portworx related pods are gone
```

2020-09-22 20:36 UTC, pault84 commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/pre-reqs.md
> +
Yes they do. the first part is so we can create disks. the 2nd part is so we can actually meter usage. but they aren't ALWAYS required. only for the AWS marketplace they are.

2020-09-22 20:51 UTC, pault84 commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +{{% content "pre-reqs.md" %}}
merged docs, they aren't shared with anything else

2020-09-22 23:59 UTC, nathan-px requested changes
more fixes

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +# Preparing your EKS Cluster
```suggestion
# Prepare your EKS Cluster
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +## Granting Portworx the needed AWS permissions
```suggestion
## Grant Portworx the needed AWS permissions
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +will create a `ServiceAcccount` in the requested namespace, which we will pass to our helmchart in the next section
```suggestion
1. Before you can create an IAMServiceAccount for Portworx, you must enable the IAM OIDC Provider for your EKS cluster. Enter the following `eksctl` command, replacing `<clustername>` with your EKS cluster and changing the `region` if you are not running in us-east-1:

     ```text
     eksctl utils associate-iam-oidc-provider --region=us-east-1 --cluster=<clustername> --approve
     ```

2. Create the IAMServiceAccount with the appropriate permissions. You need these permissions to send metering data to AWS. Enter the following `eksctl` command, changing the namespace if you are not deploying in `kube-system` and replacing `<clustername>` with your EKS cluster:

     ```text
     eksctl create iamserviceaccount --name portworx-aws --namespace kube-system --cluster <clustername> --attach-policy-arn arn:aws:iam::aws:policy/AWSMarketplaceMeteringFullAccess \
     --attach-policy-arn arn:aws:iam::aws:policy/AWSMarketplaceMeteringRegisterUsage --approve --override-existing-serviceaccounts
     ```

     This creates an `IAMServiceAccount` on Amazon `https://console.aws.amazon.com/iam/home?#/roles` and will create a `ServiceAcccount` in the requested namespace, which you will pass to your Helm chart in the next section.
```

do we need to show the URL for clarity? Maybe we can link to it instead? I'll leave it up to you.

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +
I think we need some context here. something like this

```suggestion
Once you've done X, you must configure IAM permissions in Y. You can configure these permissions in multiple ways, choose the configuration method most appropriate for you: 
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +for AWS Console go here: [AWS Console] (https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html#aws-management-console)
```suggestion
You can configure IAM permissions through the AWS CLI or console. For instructions on configuring these permissions, refer to the Amazon documentation:

* [AWS CLI] (https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html#aws-cli)
* [AWS Console] (https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html#aws-management-console)

Use the correct `namespace` and `serviceaccount` you defined in the steps above. 
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +{{</info>}}
```suggestion
{{<info>}}
**NOTE:** If you are not using instance privileges, you must also specify AWS environment variables in the Helm install parameters. Specify the following environment variables:

`--set env="AWS_ACCESS_KEY_ID=<id>\,AWS_SECRET_ACCESS_KEY=<key>"`
{{</info>}}
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Adding the helm repository
```suggestion
### Add the Helm repository
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +To add the Portworx AWS Helm repository run the following command:
```suggestion
Add the Portworx AWS Helm repository by running the following `helm` command:
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Upgrading the helm repository
```suggestion
### Upgrade the helm repository
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +```
```suggestion
To upgrade the Helm repository or to make sure you have the latest version of the Helm chart,
run the following command:

```text
helm repo update
```
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +```
Why specify `my-release`? Can we make this more generic and use <brackets>?

```suggestion
#### Install the Helm chart from the repository

Install the chart with by running the following command, specifying your own release name and substituting relevant values for your setup:

```text
helm install <your-release-name> portworx/portworx --set storage.drives="type=gp2\,size=1000" --set serviceAccount="portworx-aws"
```
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Configuration options for the helm chart.
```suggestion
### Helm chart configuration reference
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Upgrading Portworx.
```suggestion
### Upgrade Portworx
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +```
```suggestion
When Portworx releases new versions, you can upgrade Portworx by running the `upgrade` command and specifying the same options you used when you installed Portworx. For example:

```text
helm upgrade my-release portworx/portworx --set storage.drives="type=gp2\,size=1000" --set serviceAccount="portworx-aws"
```
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Un-installing Portworx
```suggestion
### Uninstall Portworx
```

2020-09-22 23:59 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +    This command removes all the Kubernetes components associated with the chart and deletes the release.
```suggestion
Perform the following steps to uninstall Portworx:

1. Edit the storage cluster:

     ```text
     kubectl -n <namespace> edit storagecluster <yourclustername>
     ```

2. Add the following lines to your YAML `spec:` section:

    ```text
    deleteStrategy:
      type: UninstallAndWipe
    ```

3. Save the spec and exit out.
4. Delete the storagecluster:

    ```text
    kubectl -n <namespace> delete storagecluster <yourclustername>
    ```

5. Once all the portworx related pods are gone,
un-install/delete the `my-release` deployment:

    ```text
    helm delete my-release
    ```
    This command removes all the Kubernetes components associated with the chart and deletes the release.
```

2020-09-23 00:00 UTC, pault84 commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +will create a `ServiceAcccount` in the requested namespace, which we will pass to our helmchart in the next section
i'll make it a call out doesn't need to be visible

2020-09-23 02:07 UTC, nathan-px requested changes
fix heading levels

2020-09-23 02:07 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +# Prepare your EKS Cluster
Where does this lead? Every heading under it is a lower level. Is it supposed to divide sections?

```suggestion
## Prepare your EKS Cluster
```

2020-09-23 02:07 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +## Grant Portworx the needed AWS permissions
```suggestion
### Grant Portworx the needed AWS permissions
```

2020-09-23 02:07 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +## Configure IAM permissions
```suggestion
### Configure IAM permissions
```

2020-09-23 02:07 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Configure with eksctl
```suggestion
#### Configure with eksctl
```

2020-09-23 02:07 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Configure with AWS CLI or AWS Console
```suggestion
#### Configure with AWS CLI or AWS Console
```

2020-09-23 02:09 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +helm repo update
```suggestion
helm repo update
```
```

2020-09-23 02:10 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Upgrade the helm repository
```suggestion
## Upgrade the helm repository
```

2020-09-23 02:10 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Installing the helm chart from the repository
```suggestion
## Installing the helm chart from the repository
```

2020-09-23 02:10 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Helm chart configuration reference
```suggestion
## Helm chart configuration reference
```

2020-09-23 02:10 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Upgrade Portworx
```suggestion
## Upgrade Portworx
```

2020-09-23 02:10 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +### Uninstall Portworx
```suggestion
## Uninstall Portworx
```

2020-09-23 02:56 UTC, nathan-px commented on content/portworx-install-with-kubernetes/cloud/aws/aws-marketplace/_index.md
> +This topic explains how to install Portworx via the Amazon Marketplace on EKS (Elastic Kubernetes Service). Follow the steps in this topic in order.
```suggestion
This topic provides instructions for installing Portworx via the Amazon Marketplace on EKS (Elastic Kubernetes Service). Follow the steps in this topic in order.
```

2020-09-23 03:25 UTC, nathan-px approved these changes

2020-09-23 03:25 UTC, merged