Add PX Security operator docs
portworx/pxdocs pull request #976
Opened 2020-09-29 01:48 UTC by ggriffiths

Signed-off-by: Grant Griffiths <grant@portworx.com>

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/portworx-install-with-kubernetes/openshift/operator/security.md
> +The operator starting with versions 1.4.0 and greater has first class support for Portworx Security in the `StorageCluster` spec. The enable Portworx Security, the only configuration needed is the fo
*To enable ...

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/portworx-install-with-kubernetes/openshift/operator/security.md
> +Once security is enabled, the opertator will automationally generate the following:
*operator
*automatically

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/reference/CRD/storage-cluster.md
> +
Let's also add the `spec.security` schema under "StorageCluster Schema" section on this page.

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-enabling-security.md
> +### Using StorageCluster security spec with auto-generated secrets
Now with the operator way of enabling security we don't need to generate shared secret, add to px spec and generate tokens. So some how we should merge step 1-3 from this page (https://docs.portworx.com/cloud-references/security/kubernetes/shared-secret-model/) for operator.

Same for multi-tenancy - https://docs.portworx.com/cloud-references/security/kubernetes/shared-secret-model-multitenancy/

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-enabling-security.md
> +### Using environment variables only
I think we should remove this entirely from the operator method of installation.

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/portworx-install-with-kubernetes/openshift/operator/security.md
> +---
Let's only keep this doc under the security page. 
Now that operator is available for non-openshift distros, we will start moving generic docs to their respective sections. Distro sections will only have installation steps.

Combine this content with the steps in security section.

2020-09-29 19:39 UTC, piyush-nimbalkar commented on content/portworx-install-with-kubernetes/openshift/operator/security.md
> +## Disabling guest role access:
We can create a separate page for tweaking the security configuration and put the below content there.
May be at the end of enabling security and deploying apps.

2020-09-29 19:52 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/openshift/operator/security.md
> +Once security is enabled, the opertator will automationally generate the following:
Wow, not sure how I came up with those haha

2020-09-30 01:29 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> -### Example
Removed this, as we do a better job of giving an example in the reference architecture page.

2020-09-30 21:48 UTC, nathan-px requested changes
see comments

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +### Disabling guest role access
I've been slowly changing these as I go. We should remove gerunds from headings and titles while we're here. It makes them more compact and easier to read when they're in the sidebar or scrollspy. 

```suggestion
### Disable guest role access
```

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +For fine-grained control over the system.guest role, you can set guestAccess to `Managed`. This will tell the operator to stop updating the [system guest role](/concepts/authorization/overview#guest-
These tasks should always include a clear instruction for the user. the idea is to separate out the explanation for what this is/does/why you want to do it and the instructions for how exactly to do it:

```suggestion
You can exercise finer control over the system.guest role by setting it `managed` mode. This instructs the Operator to stop updating the [system guest role](/concepts/authorization/overview#guest-access), allowing you to [customize it yourself](/reference/cli/role/#re-enabling-the-system-guest-role).

To enter `managed` mode, set the value of the `spec.security.auth.guestAccess` field to `managed`:
```

review the other sections and see if they can be separated in the same manner.

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +title: "Customizing Security in Portworx"
```suggestion
title: "Customize Security in Portworx"
```

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +There are a few different environment variables needed to start Portworx with security enabled. If you have previously started Portworx security with environment variables, the same method will work
Is this saying that you don't need to migrate from env vars to StorageCluster if you did this? I don't think so, so I'm not following this sentence:

> If you have previously started Portworx security with environment variables, the same method will work with the operator 1.4 and later.

I assume this is what the steps show you how to do? If so, we should be more explicit about that. 
> However, if you wish to start using the `StorageCluster` security spec, here are how the environment variables map to spec fields.

Why should they familiarize themselves with this spec? what's the relation between that spec and here?

>First, familiarize yourself with the Security spec in the [StorageCluster](/reference/crd/storage-cluster) article.

```suggestion
In order For Portworx to start with security enabled, it requires a few different environment variables. If you have previously started Portworx security with environment variables, the same method will work with the operator 1.4 and later. However, if you wish to start using the `StorageCluster` security spec, you must map the environment variables to spec fields. 

First, familiarize yourself with the Security spec in the [StorageCluster](/reference/crd/storage-cluster) article.
```

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-enabling-security.md
> +The operator starting with versions 1.4.0 and greater has first class support for Portworx Security in the `StorageCluster` spec. This means that the operator will auto-generate the following for you
I _think_ we've established that `Operator` should be capitalized. I think this is how Kubernetes does it. Happy to discuss if you're of a different opinion. 

Is `first-class support` a term within K8s, or did we coin it here? If the latter, I'd recommend we drop it in favor of just explaining it.

```suggestion
The Operator, starting with versions 1.4.0 and greater, includes first-class support for Portworx Security in the `StorageCluster` spec. This means that the operator will auto-generate the following for you if security is enabled:
```

2020-09-30 21:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-enabling-security.md
> +3. User token stored under the secret `px-user-token`
```suggestion
* Shared Secret stored under the secret `px-shared-secret`
* Admin token stored under the secret `px-admin-token` 
* User token stored under the secret `px-user-token`
```

2020-10-01 22:58 UTC, ggriffiths commented on content/cloud-references/security/kubernetes/shared-secret-model-operator/example-application.md
> +---
It's not yet. I'll make it shared.

2020-10-01 23:35 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> -### Example
Added the example back in under `Enabling authorization with a Portworx Manifest`

2020-10-01 23:44 UTC, ggriffiths commented on content/cloud-references/security/kubernetes/shared-secret-model-operator/_index.md
> +method to requests, further providing deployers with a complete secured system.
Reworked this.

2020-10-01 23:51 UTC, ggriffiths commented on content/cloud-references/security/kubernetes/shared-secret-model-operator/storageclass.md
> +title: "Step 3: StorageClass Setup"
Made this into steps

2020-10-01 23:51 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> +1. Create a secret:
Fixed this.

2020-10-02 17:48 UTC, nathan-px commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +---
all shared content should have `hidden: true` in the frontmatter

2020-10-03 00:02 UTC, ggriffiths commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +---
made all of the `cloud-references-security-kubernetes-*` hidden: true.

2020-10-08 20:35 UTC, lpabon requested changes

2020-10-08 20:35 UTC, lpabon commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> +      --from-literal=system-secret='RmlqRSfh9' \
I would suggest not having any secret keys as examples. Have them generated and saved in a variable, which would be random, them use them.

2020-10-08 20:35 UTC, lpabon commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> +      --from-literal=system-secret='RmlqRSfh9' \
This avoids users copying the information and using the same keys

2020-10-08 20:35 UTC, lpabon commented on content/portworx-install-with-kubernetes/storage-operations/csi/_index.md
> +    kubectl get secret px-user-token -o yaml
Can we provide here the command to copy the token into a variable automatically, then we can use that variable in the next example. That way they can just copy paste the examples here and they would work for their system

2020-10-08 20:35 UTC, lpabon commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +  --from-literal=shared-secret=<Existing Shared Secret Value>
Same here. Generate, save in a var, then use

2020-10-08 22:27 UTC, ggriffiths commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +  --from-literal=shared-secret=<Existing Shared Secret Value>
I'm not sure we want to generate this secret in this case. This case is for allowing users to create a k8s secret with their pre-existing shared secret.

If they do not follow this step, we just generate the secret for them.

2020-10-08 22:28 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/storage-operations/csi/_index.md
> +    kubectl get secret px-user-token -o yaml
Added this

2020-10-08 22:43 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> +      --from-literal=system-secret='RmlqRSfh9' \
Fixed this

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/manage.md
> +    USER_TOKEN=$(kubectl get secrets px-user-token -n default -o json | jq -r '.data["auth-token"]' | base64 -d)
Change the namespace from `default` to `kube-system` or `<cluster_namespace>`. Most users would create StorageCluster in kube-system namespace.
Additionally if you want, we can always say in the line above - Assuming StorageCluster is created in `kube-system` namespace..

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/reference/CRD/storage-cluster.md
> +      guestAccess: 'Enabled'
`Disabled` as per the example title?

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/reference/CRD/storage-cluster.md
> +    useAll: true
We can skip this

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/reference/CRD/storage-cluster.md
> +| spec.<br>security | An object for specifying Portworx Security configurations. Refer to the Operator Security page for more details. | `object` | None |
May be put a link to the operator security page?

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/reference/CRD/storage-cluster.md
> +| spec.<br>security | An object for specifying Portworx Security configurations. Refer to the Operator Security page for more details. | `object` | None |
Can we add a section for the Security Configuration on this page? 
Checkout other sections here and explain all the fields in the security section.

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +* Portworx Operator 1.4.0 or later
Just use 1.4 to be consistent with other places we have mention 1.4 operator.

2020-10-12 23:14 UTC, piyush-nimbalkar commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-enabling-security.md
> +* You must have Portworx Operator 1.4.0 or greater
Just use 1.4 for consistency

2020-10-13 18:25 UTC, ggriffiths commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +    - name: "PX_SHARED_SECRET"
Yes, good point

2020-10-13 19:11 UTC, ggriffiths commented on content/reference/CRD/storage-cluster.md
> +| spec.<br>security | An object for specifying Portworx Security configurations. Refer to the Operator Security page for more details. | `object` | None |
Added this

2020-10-13 19:14 UTC, ggriffiths commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-customizing-operator-security.md
> +This optional document guides you through customizing your Portworx Operator Security install to fit specific needs.
Having optional in the title felt crowded in the nav bar. I'll move it to be after the example app.

2020-10-13 19:34 UTC, ggriffiths commented on content/cloud-references/security/kubernetes/shared-secret-model-multitenancy/generating-tokens.md
> +title: "Step 2: Generate multitenant tokens"
Yes, because this guide follows the CSI multitenant model. You must create separate tokens in this case, because the user is using multiple namespaces with separate tokens in each space.

2020-10-13 19:56 UTC, ggriffiths commented on content/shared/cloud-references-security-kubernetes-shared-secret-model-example-storageclass.md
> +`px-user-token` in the `portworx` namespace. Now you can create a storage class
Fixed this

2020-10-13 23:07 UTC, piyush-nimbalkar approved these changes
Looks good to me.

2020-10-14 00:50 UTC, nathan-px approved these changes
approved, with some comments

2020-10-14 03:43 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> +## Step by step guide
I'll delete this sentence. I wrote this section before the operator specific docs, which has instructions on disabling the gust role.

2020-10-14 18:15 UTC, lpabon approved these changes

2020-10-14 18:16 UTC, ggriffiths commented on content/portworx-install-with-kubernetes/operate-and-maintain-on-kubernetes/authorization/enable.md
> -## Enabling authorization
Done

2020-10-14 18:36 UTC, merged